/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AkashApplications.src;


import AkashApplications.JsonParser.CustomJsonParser;
import AkashApplications.networkmanager.SendBulkRequest;
import AkashApplications.networkmanager.SendRequest;
import AkashApplications.networkmanager.ServerConstants;
import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.omg.CORBA.ServerRequest;

/**
 *
 * @author akash
 */
public class MainUI extends javax.swing.JFrame {

    /**
     * Creates new form MainUI
     */
    public static final String TITLE = "Inventory Management";
    public MainUI() {
        initComponents();
        
        setPanelVisibility(StockPane);
       
        BulkItemTable.getColumnModel().getColumn(6).setMaxWidth(0);
        BulkItemTable.getColumnModel().getColumn(6).setMinWidth(0);
        BulkItemTable.getColumnModel().getColumn(6).setPreferredWidth(0);
        
        setTitle(TITLE+" - Stock");
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddSingleItemPane = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        productIDAddSingle = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        designNameAddSingle = new javax.swing.JTextField();
        rackNoAddSingle = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        subRackNoAddSingle = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        qtyAddSingle = new javax.swing.JTextField();
        AddSingleProgress = new javax.swing.JProgressBar();
        AddSingleProgressReport = new javax.swing.JLabel();
        saveAddSingle = new javax.swing.JButton();
        barcodeAddSingle = new javax.swing.JLabel();
        generateBarcodeAddSingle = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        textureAddSingle = new javax.swing.JTextField();
        AddBulkItemPane = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        productIDAddBulk = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        designNameAddBulk = new javax.swing.JTextField();
        qtyAddBulk = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        subRackNoAddBulk = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        rackNoAddBulk = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        barcodeAddBulk = new javax.swing.JLabel();
        addBtnAddBulk = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        BulkItemTable = new javax.swing.JTable();
        progressReportAddBulk = new javax.swing.JLabel();
        progressBarAddBulk = new javax.swing.JProgressBar();
        saveAllBtnAddBulk = new javax.swing.JButton();
        textureAddBulk = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        StockSummaryPane = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        productIDSSummary = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        designNameSSummary = new javax.swing.JTextField();
        searchBtnSSummary = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        StockSummaryTable = new javax.swing.JTable();
        StockSummaryProgress = new javax.swing.JProgressBar();
        StockSummaryProgressReport = new javax.swing.JLabel();
        StockPane = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        productID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        rackNo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        subRackNo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        qty = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        designName = new javax.swing.JTextField();
        updateCancleBtn = new javax.swing.JButton();
        editUpdateBtn = new javax.swing.JButton();
        mainUiProgress = new javax.swing.JProgressBar();
        mainUiProgressReport = new javax.swing.JLabel();
        searchBtn = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        texture = new javax.swing.JTextField();
        AddClientPanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inventory Management");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AddSingleItemPane.setPreferredSize(new java.awt.Dimension(810, 540));

        jLabel8.setText("Product ID");

        productIDAddSingle.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                productIDAddSingleInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        productIDAddSingle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                productIDAddSingleKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                productIDAddSingleKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                productIDAddSingleKeyReleased(evt);
            }
        });

        jLabel9.setText("Design Name");

        rackNoAddSingle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rackNoAddSingleActionPerformed(evt);
            }
        });

        jLabel10.setText("Sub Rack Number");

        jLabel11.setText("Rack Number");
        jLabel11.setPreferredSize(new java.awt.Dimension(73, 15));

        jLabel12.setText("Stock Quantity");

        AddSingleProgressReport.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        AddSingleProgressReport.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        saveAddSingle.setText("Save");
        saveAddSingle.setEnabled(false);
        saveAddSingle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAddSingleActionPerformed(evt);
            }
        });

        generateBarcodeAddSingle.setText("Generate Barcode");
        generateBarcodeAddSingle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateBarcodeAddSingleActionPerformed(evt);
            }
        });

        jLabel19.setText("Texture");
        jLabel19.setPreferredSize(new java.awt.Dimension(73, 15));

        textureAddSingle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textureAddSingleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddSingleItemPaneLayout = new javax.swing.GroupLayout(AddSingleItemPane);
        AddSingleItemPane.setLayout(AddSingleItemPaneLayout);
        AddSingleItemPaneLayout.setHorizontalGroup(
            AddSingleItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddSingleItemPaneLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(AddSingleItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddSingleItemPaneLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(AddSingleItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AddSingleItemPaneLayout.createSequentialGroup()
                                .addGroup(AddSingleItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(AddSingleItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(AddSingleItemPaneLayout.createSequentialGroup()
                                        .addComponent(rackNoAddSingle, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(subRackNoAddSingle, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(qtyAddSingle, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(AddSingleItemPaneLayout.createSequentialGroup()
                                        .addComponent(productIDAddSingle, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(designNameAddSingle)))
                                .addGap(29, 29, 29))
                            .addGroup(AddSingleItemPaneLayout.createSequentialGroup()
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(textureAddSingle, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddSingleItemPaneLayout.createSequentialGroup()
                        .addComponent(generateBarcodeAddSingle)
                        .addGap(18, 18, 18)
                        .addComponent(saveAddSingle, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(AddSingleProgress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddSingleProgressReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(AddSingleItemPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(barcodeAddSingle, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AddSingleItemPaneLayout.setVerticalGroup(
            AddSingleItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddSingleItemPaneLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(AddSingleItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddSingleItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(productIDAddSingle, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AddSingleItemPaneLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(AddSingleItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(designNameAddSingle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(AddSingleItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(AddSingleItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rackNoAddSingle, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AddSingleItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(AddSingleItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(subRackNoAddSingle)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(AddSingleItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(qtyAddSingle, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(AddSingleItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textureAddSingle, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(AddSingleItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveAddSingle)
                    .addComponent(generateBarcodeAddSingle))
                .addGap(30, 30, 30)
                .addComponent(AddSingleProgress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AddSingleProgressReport, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(barcodeAddSingle, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(115, Short.MAX_VALUE))
        );

        getContentPane().add(AddSingleItemPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        AddBulkItemPane.setPreferredSize(new java.awt.Dimension(810, 540));

        jLabel13.setText("Product ID");

        productIDAddBulk.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                productIDAddBulkInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        productIDAddBulk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                productIDAddBulkKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                productIDAddBulkKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                productIDAddBulkKeyReleased(evt);
            }
        });

        jLabel14.setText("Design Name");

        jLabel15.setText("Stock Quantity");

        jLabel16.setText("Sub Rack Number");

        rackNoAddBulk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rackNoAddBulkActionPerformed(evt);
            }
        });

        jLabel17.setText("Rack Number");
        jLabel17.setPreferredSize(new java.awt.Dimension(73, 15));

        addBtnAddBulk.setText("Add");
        addBtnAddBulk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnAddBulkActionPerformed(evt);
            }
        });

        BulkItemTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Design", "Rack", "Sub Rack", "Texture", "Quantity", "Barcode"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(BulkItemTable);
        if (BulkItemTable.getColumnModel().getColumnCount() > 0) {
            BulkItemTable.getColumnModel().getColumn(6).setResizable(false);
            BulkItemTable.getColumnModel().getColumn(6).setPreferredWidth(0);
        }

        progressReportAddBulk.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N

        saveAllBtnAddBulk.setText("Save All");
        saveAllBtnAddBulk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAllBtnAddBulkActionPerformed(evt);
            }
        });

        textureAddBulk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textureAddBulkActionPerformed(evt);
            }
        });

        jLabel18.setText("Texture");
        jLabel18.setPreferredSize(new java.awt.Dimension(73, 15));

        javax.swing.GroupLayout AddBulkItemPaneLayout = new javax.swing.GroupLayout(AddBulkItemPane);
        AddBulkItemPane.setLayout(AddBulkItemPaneLayout);
        AddBulkItemPaneLayout.setHorizontalGroup(
            AddBulkItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddBulkItemPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddBulkItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5)
                    .addGroup(AddBulkItemPaneLayout.createSequentialGroup()
                        .addGroup(AddBulkItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(progressReportAddBulk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(progressBarAddBulk, javax.swing.GroupLayout.DEFAULT_SIZE, 784, Short.MAX_VALUE)
                            .addComponent(saveAllBtnAddBulk, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddBulkItemPaneLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(AddBulkItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddBulkItemPaneLayout.createSequentialGroup()
                        .addGroup(AddBulkItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(AddBulkItemPaneLayout.createSequentialGroup()
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textureAddBulk, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(addBtnAddBulk, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(68, 68, 68)
                        .addComponent(barcodeAddBulk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(AddBulkItemPaneLayout.createSequentialGroup()
                        .addGroup(AddBulkItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AddBulkItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AddBulkItemPaneLayout.createSequentialGroup()
                                .addComponent(productIDAddBulk, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(designNameAddBulk))
                            .addGroup(AddBulkItemPaneLayout.createSequentialGroup()
                                .addComponent(rackNoAddBulk, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(subRackNoAddBulk, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(qtyAddBulk, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(35, 35, 35))
        );
        AddBulkItemPaneLayout.setVerticalGroup(
            AddBulkItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddBulkItemPaneLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(AddBulkItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddBulkItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(productIDAddBulk, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AddBulkItemPaneLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(AddBulkItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(designNameAddBulk, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(AddBulkItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(AddBulkItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rackNoAddBulk, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AddBulkItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(AddBulkItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(subRackNoAddBulk)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(AddBulkItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(qtyAddBulk, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(AddBulkItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(barcodeAddBulk, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(AddBulkItemPaneLayout.createSequentialGroup()
                        .addGroup(AddBulkItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textureAddBulk, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addBtnAddBulk)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(saveAllBtnAddBulk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(progressBarAddBulk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progressReportAddBulk, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(AddBulkItemPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel6.setText("Product ID");

        productIDSSummary.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                productIDSSummaryInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        productIDSSummary.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                productIDSSummaryKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                productIDSSummaryKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                productIDSSummaryKeyReleased(evt);
            }
        });

        jLabel7.setText("Design Name");

        designNameSSummary.setEnabled(false);

        searchBtnSSummary.setText("Search");

        StockSummaryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SL. No.", "Product ID", "Design", "Rack", "Sub Rack", "Texture", "Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        StockSummaryTable.setColumnSelectionAllowed(true);
        jScrollPane2.setViewportView(StockSummaryTable);
        StockSummaryTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        StockSummaryProgressReport.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N

        javax.swing.GroupLayout StockSummaryPaneLayout = new javax.swing.GroupLayout(StockSummaryPane);
        StockSummaryPane.setLayout(StockSummaryPaneLayout);
        StockSummaryPaneLayout.setHorizontalGroup(
            StockSummaryPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StockSummaryPaneLayout.createSequentialGroup()
                .addGroup(StockSummaryPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(StockSummaryPaneLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(searchBtnSSummary, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(StockSummaryPaneLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(productIDSSummary, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(designNameSSummary, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)))
                .addGap(37, 37, 37))
            .addGroup(StockSummaryPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(StockSummaryPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 775, Short.MAX_VALUE)
                    .addComponent(StockSummaryProgress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(StockSummaryProgressReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        StockSummaryPaneLayout.setVerticalGroup(
            StockSummaryPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StockSummaryPaneLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(StockSummaryPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StockSummaryPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(productIDSSummary, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(StockSummaryPaneLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(StockSummaryPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(designNameSSummary, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchBtnSSummary)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(StockSummaryProgress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StockSummaryProgressReport, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(StockSummaryPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 540));

        jLabel2.setText("Product ID");

        productID.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                productIDInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        productID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                productIDKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                productIDKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                productIDKeyReleased(evt);
            }
        });

        jLabel3.setText("Rack Number");
        jLabel3.setPreferredSize(new java.awt.Dimension(73, 15));

        rackNo.setEnabled(false);
        rackNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rackNoActionPerformed(evt);
            }
        });

        jLabel1.setText("Sub Rack Number");

        subRackNo.setEnabled(false);

        jLabel4.setText("Stock Quantity");

        qty.setEnabled(false);

        jLabel5.setText("Design Name");

        designName.setEnabled(false);

        updateCancleBtn.setText("Cancel");
        updateCancleBtn.setEnabled(false);

        editUpdateBtn.setText("Edit");
        editUpdateBtn.setEnabled(false);
        editUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editUpdateBtnActionPerformed(evt);
            }
        });

        mainUiProgressReport.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        mainUiProgressReport.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        searchBtn.setText("Search");
        searchBtn.setEnabled(false);

        jLabel20.setText("Texture");
        jLabel20.setPreferredSize(new java.awt.Dimension(73, 15));

        texture.setEnabled(false);
        texture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textureActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout StockPaneLayout = new javax.swing.GroupLayout(StockPane);
        StockPane.setLayout(StockPaneLayout);
        StockPaneLayout.setHorizontalGroup(
            StockPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StockPaneLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(StockPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StockPaneLayout.createSequentialGroup()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(texture, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(StockPaneLayout.createSequentialGroup()
                        .addGroup(StockPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(StockPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(StockPaneLayout.createSequentialGroup()
                                .addComponent(rackNo, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(subRackNo, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(qty, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(StockPaneLayout.createSequentialGroup()
                                .addComponent(productID, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(designName)))
                        .addGap(41, 41, 41))))
            .addGroup(StockPaneLayout.createSequentialGroup()
                .addGroup(StockPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StockPaneLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(editUpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(updateCancleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(StockPaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(mainUiProgress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(StockPaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(mainUiProgressReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        StockPaneLayout.setVerticalGroup(
            StockPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StockPaneLayout.createSequentialGroup()
                .addGroup(StockPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StockPaneLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(StockPaneLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(StockPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(productID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StockPaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(designName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(StockPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(StockPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rackNo, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                    .addGroup(StockPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(StockPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(subRackNo)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(StockPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(qty, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(StockPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(texture, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(116, 116, 116)
                .addGroup(StockPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateCancleBtn)
                    .addComponent(editUpdateBtn)
                    .addComponent(searchBtn))
                .addGap(30, 30, 30)
                .addComponent(mainUiProgress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mainUiProgressReport, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(StockPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        AddClientPanel.setPreferredSize(new java.awt.Dimension(810, 540));

        javax.swing.GroupLayout AddClientPanelLayout = new javax.swing.GroupLayout(AddClientPanel);
        AddClientPanel.setLayout(AddClientPanelLayout);
        AddClientPanelLayout.setHorizontalGroup(
            AddClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );
        AddClientPanelLayout.setVerticalGroup(
            AddClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        getContentPane().add(AddClientPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jMenu1.setText("File");

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setText("Download Barcodes");
        jMenu1.add(jMenuItem5);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setText("Print Chalan");
        jMenu1.add(jMenuItem6);
        jMenu1.add(jSeparator1);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem7.setText("About");
        jMenu1.add(jMenuItem7);

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem8.setText("Exit");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem8);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Stock");

        jMenuItem11.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem11.setText("Stock");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem11);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Stock Summary");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Add Single Item");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Add Bulk Item ");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("Sale Record");
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Client");

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem9.setText("Add Client");
        jMenu3.add(jMenuItem9);

        jMenuItem10.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem10.setText("Favourite Client");
        jMenu3.add(jMenuItem10);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rackNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rackNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rackNoActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void productIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_productIDKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_productIDKeyTyped

    private void productIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_productIDKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == 10)
            editUpdateBtn.setEnabled(true);
        else
            editUpdateBtn.setEnabled(false);
    }//GEN-LAST:event_productIDKeyPressed

    private void productIDInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_productIDInputMethodTextChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_productIDInputMethodTextChanged

    private void productIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_productIDKeyReleased
        // TODO add your handling code here:
        if(productID.getText().length() == 0)
            searchBtn.setEnabled(false);
        else
            searchBtn.setEnabled(true);
    }//GEN-LAST:event_productIDKeyReleased

    private void productIDSSummaryInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_productIDSSummaryInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_productIDSSummaryInputMethodTextChanged

    private void productIDSSummaryKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_productIDSSummaryKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_productIDSSummaryKeyTyped

    private void productIDSSummaryKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_productIDSSummaryKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_productIDSSummaryKeyPressed

    private void productIDSSummaryKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_productIDSSummaryKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_productIDSSummaryKeyReleased

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        setTitle(TITLE + " - Stock");
        setPanelVisibility(StockPane);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        setTitle(TITLE + " - Stock Summary");
        setPanelVisibility(StockSummaryPane);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void productIDAddSingleInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_productIDAddSingleInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_productIDAddSingleInputMethodTextChanged

    private void productIDAddSingleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_productIDAddSingleKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_productIDAddSingleKeyTyped

    private void productIDAddSingleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_productIDAddSingleKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_productIDAddSingleKeyPressed

    private void productIDAddSingleKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_productIDAddSingleKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_productIDAddSingleKeyReleased

    private void rackNoAddSingleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rackNoAddSingleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rackNoAddSingleActionPerformed

    private void productIDAddBulkInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_productIDAddBulkInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_productIDAddBulkInputMethodTextChanged

    private void productIDAddBulkKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_productIDAddBulkKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_productIDAddBulkKeyTyped

    private void productIDAddBulkKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_productIDAddBulkKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_productIDAddBulkKeyPressed

    private void productIDAddBulkKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_productIDAddBulkKeyReleased
        barcodeAddBulk.setIcon(null);
    }//GEN-LAST:event_productIDAddBulkKeyReleased

    private void rackNoAddBulkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rackNoAddBulkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rackNoAddBulkActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        setTitle(TITLE + " - Add Bulk Product");
        setPanelVisibility(AddBulkItemPane);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        setTitle(TITLE + " - Add Single Product");
        setPanelVisibility(AddSingleItemPane);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void editUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editUpdateBtnActionPerformed
        // TODO add your handling code here:
        if(editUpdateBtn.getText().equalsIgnoreCase("Edit"))
        {
            designName.setEnabled(true);
            rackNo.setEnabled(true);
            subRackNo.setEnabled(true);
            texture.setEnabled(true);
            qty.setEnabled(true);
            editUpdateBtn.setText("Update");
        }
        else if(editUpdateBtn.getText().equalsIgnoreCase("Update"))
        {
            try {
                
                designName.setEnabled(false);
                rackNo.setEnabled(false);
                subRackNo.setEnabled(false);
                texture.setEnabled(false);
                qty.setEditable(false);
                editUpdateBtn.setText("Edit");
            } catch (Exception ex) {
                Logger.getLogger(MainUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
            
    }//GEN-LAST:event_editUpdateBtnActionPerformed

    private void generateBarcodeAddSingleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateBarcodeAddSingleActionPerformed
        // TODO add your handling code here:
        String pId = productIDAddSingle.getText();
        String design = designNameAddSingle.getText();
        String rack = rackNoAddSingle.getText();
        String subRack = subRackNoAddSingle.getText();
        String qty = qtyAddSingle.getText();
        String desc = textureAddSingle.getText();
        if(pId.equals(""))
            JOptionPane.showMessageDialog(null,"Enter Product ID","Alert",JOptionPane.WARNING_MESSAGE);
        else
            if(design.equals(""))
                JOptionPane.showMessageDialog(null,"Enter Design name","Alert",JOptionPane.WARNING_MESSAGE);
        else
            if(rack.equals(""))
                JOptionPane.showMessageDialog(null,"Enter rack number","Alert",JOptionPane.WARNING_MESSAGE);
            else
                if(!validateNumberInput(rack))
                    JOptionPane.showMessageDialog(null,"Enter valid rack number","Alert",JOptionPane.WARNING_MESSAGE);
        else
            if(subRack.equals(""))
                JOptionPane.showMessageDialog(null,"Enter sub rack number","Alert",JOptionPane.WARNING_MESSAGE);
            else
                if(!validateNumberInput(subRack))
                    JOptionPane.showMessageDialog(null,"Enter valid sub rack number","Alert",JOptionPane.WARNING_MESSAGE);
        else
            if(qty.equals(""))
                JOptionPane.showMessageDialog(null,"Enter stock quantity","Alert",JOptionPane.WARNING_MESSAGE);
            else
                if(!validateNumberInput(qty))
                    JOptionPane.showMessageDialog(null,"Enter valid stock quantity count","Alert",JOptionPane.WARNING_MESSAGE);
        else
            if(desc.equals(""))
                JOptionPane.showMessageDialog(null,"Enter product description","Alert",JOptionPane.WARNING_MESSAGE);
        else
            {
            try {
                if(new GenerateBarcode(pId, pId).encode())
                {
                    barcodeAddSingle.setIcon(null);
                    ImageIcon iconLogo = new ImageIcon(new ImageIcon("Barcodes" + File.separator + pId+".jpg").getImage().getScaledInstance(barcodeAddSingle.getWidth(), barcodeAddSingle.getHeight(), Image.SCALE_SMOOTH));
                    barcodeAddSingle.setIcon(iconLogo);
                    saveAddSingle.setEnabled(true);
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null,"Failed to generate barcode\n\nError : "+ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
            }
            }
    }//GEN-LAST:event_generateBarcodeAddSingleActionPerformed

    private void saveAddSingleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAddSingleActionPerformed
        try {
            // TODO add your handling code here:
            String pId = productIDAddSingle.getText();
            String design = designNameAddSingle.getText();
            String rack = rackNoAddSingle.getText();
            String subRack = subRackNoAddSingle.getText();
            String qty = qtyAddSingle.getText();
            String texture = textureAddSingle.getText();
            
            //new ProgressBarUpdate(AddSingleProgress, AddSingleProgressReport).doInBackground();
            HashMap<String,String> map = new HashMap<String,String>();
            map.put("pid",pId);
            map.put("design",design);
            map.put("rack",rack);
            map.put("subrack",subRack);
            map.put("texture",texture);
            map.put("qty",qty);
            map.put("barcode",GenerateBarcode.convertToBase64("Barcodes" + File.separator + pId+".jpg"));
            String s = new SendRequest(AddSingleProgressReport,AddSingleProgress,map,ServerConstants.ADD_PRODUCT).serverResponse();
            CustomJsonParser parser = new CustomJsonParser(s);
            if(parser.getStatus())
            {
                AddSingleProgress.setValue(0);
                AddSingleProgressReport.setText("");
                
                productIDAddSingle.setText("");
                designNameAddSingle.setText("");
                rackNoAddSingle.setText("");
                subRackNoAddSingle.setText("");
                qtyAddSingle.setText("");
                textureAddSingle.setText("");
                saveAddSingle.setEnabled(false);
                barcodeAddSingle.setIcon(null);
            }
            else
            {
                AddSingleProgress.setValue(0);
                AddSingleProgressReport.setText(parser.getReason());
            }
            
        } catch (Exception ex) {
            Logger.getLogger(MainUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_saveAddSingleActionPerformed

    private void addBtnAddBulkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnAddBulkActionPerformed
        // TODO add your handling code here:
        String pId = productIDAddBulk.getText();
        String design = designNameAddBulk.getText();
        String rack = rackNoAddBulk.getText();
        String subRack = subRackNoAddBulk.getText();
        String qty = qtyAddBulk.getText();
        String desc = textureAddBulk.getText();
        if(pId.equals(""))
            JOptionPane.showMessageDialog(null,"Enter Product ID","Alert",JOptionPane.WARNING_MESSAGE);
        else
            if(design.equals(""))
                JOptionPane.showMessageDialog(null,"Enter Design name","Alert",JOptionPane.WARNING_MESSAGE);
        else
            if(rack.equals(""))
                JOptionPane.showMessageDialog(null,"Enter rack number","Alert",JOptionPane.WARNING_MESSAGE);
            else
                if(!validateNumberInput(rack))
                    JOptionPane.showMessageDialog(null,"Enter valid rack number","Alert",JOptionPane.WARNING_MESSAGE);
        else
            if(subRack.equals(""))
                JOptionPane.showMessageDialog(null,"Enter sub rack number","Alert",JOptionPane.WARNING_MESSAGE);
            else
                if(!validateNumberInput(subRack))
                    JOptionPane.showMessageDialog(null,"Enter valid sub rack number","Alert",JOptionPane.WARNING_MESSAGE);
        else
            if(qty.equals(""))
                JOptionPane.showMessageDialog(null,"Enter stock quantity","Alert",JOptionPane.WARNING_MESSAGE);
            else
                if(!validateNumberInput(qty))
                    JOptionPane.showMessageDialog(null,"Enter valid stock quantity count","Alert",JOptionPane.WARNING_MESSAGE);
        else
            if(desc.equals(""))
                JOptionPane.showMessageDialog(null,"Enter product description","Alert",JOptionPane.WARNING_MESSAGE);
        else
            {
            try {
                if(new GenerateBarcode(pId, pId).encode())
                {
                    barcodeAddBulk.setIcon(null);
                    ImageIcon iconLogo = new ImageIcon(new ImageIcon("Barcodes" + File.separator + pId+".jpg").getImage().getScaledInstance(barcodeAddBulk.getWidth(), barcodeAddBulk.getHeight(), Image.SCALE_SMOOTH));
                    barcodeAddBulk.setIcon(iconLogo);
                    
                    DefaultTableModel model = (DefaultTableModel) BulkItemTable.getModel();
                    Object[] row = {pId,design,rack,subRack,desc,qty,GenerateBarcode.convertToBase64("Barcodes" + File.separator + pId+".jpg")};
                    model.addRow(row);
                    
                    productIDAddBulk.setText("");
                    designNameAddBulk.setText("");
                    rackNoAddBulk.setText("");
                    subRackNoAddBulk.setText("");
                    qtyAddBulk.setText("");
                    textureAddBulk.setText("");
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null,"Failed to generate barcode\n\nError : "+ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
            }
         }
    }//GEN-LAST:event_addBtnAddBulkActionPerformed

    private void textureAddSingleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textureAddSingleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textureAddSingleActionPerformed

    private void textureAddBulkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textureAddBulkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textureAddBulkActionPerformed

    private void textureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textureActionPerformed

    private void saveAllBtnAddBulkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAllBtnAddBulkActionPerformed
        // TODO add your handling code here:
       ArrayList<ProductModel> list = new ArrayList<>();
       int progressInterval = 100/BulkItemTable.getRowCount();
       progressBarAddBulk.setValue(progressInterval);
       progressReportAddBulk.setText("Preparing Table");
       for(int i=0; i<BulkItemTable.getRowCount(); i++)
       {
           try {
               list.add(new ProductModel(String.valueOf(BulkItemTable.getValueAt(i, 0)),
                       String.valueOf(BulkItemTable.getValueAt(i, 1)),
                       String.valueOf(BulkItemTable.getValueAt(i, 2)),
                       String.valueOf(BulkItemTable.getValueAt(i, 3)),
                       String.valueOf(BulkItemTable.getValueAt(i, 4)),
                       String.valueOf(BulkItemTable.getValueAt(i, 5)),
                       String.valueOf(BulkItemTable.getValueAt(i, 6))));
               
               new ProgressBarUpdate(progressBarAddBulk, progressReportAddBulk, "Preparing Table : "+(i+1)+"/"+BulkItemTable.getRowCount(), progressInterval).setProgerss();
           } catch (Exception ex) {
               System.err.println(ex.getMessage());
           }
       }
       progressBarAddBulk.setValue(100);
       progressBarAddBulk.setValue(0);
       progressReportAddBulk.setText("Requestings server...");
       
       for(int i = 0; i < list.size(); i++ )
       {
           try {
               new ProgressBarUpdate(progressBarAddBulk, progressReportAddBulk, "Saving Product "+(i+1)+" out of "+list.size()+"...", progressInterval).setProgerss();
               ProductModel pm = list.get(i);
               HashMap<String,String> map = new HashMap<>();
               map.put("pid",pm.getPid());
               map.put("design",pm.getDesign());
               map.put("rack",pm.getRack());
               map.put("subrack",pm.getSubrack());
               map.put("texture",pm.getTexture());
               map.put("qty",pm.getQty());
               map.put("barcode",pm.getBarcode());
               
               String s = new SendBulkRequest(map,ServerConstants.ADD_PRODUCT).serverResponse();
               CustomJsonParser jsonParser = new CustomJsonParser(s);
               if(!jsonParser.getStatus())
               {
                   JOptionPane.showMessageDialog(null,"Request was rejected by server\n\nError : "+ jsonParser.getReason(),"Error",JOptionPane.ERROR_MESSAGE);
                   break;
               }
           } catch (Exception ex) {
               System.err.println(ex.getMessage());
           }
       }
       
    progressBarAddBulk.setValue(100);
    progressReportAddBulk.setText("All products were saved successfully...");
    }//GEN-LAST:event_saveAllBtnAddBulkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddBulkItemPane;
    private javax.swing.JPanel AddClientPanel;
    private javax.swing.JPanel AddSingleItemPane;
    private javax.swing.JProgressBar AddSingleProgress;
    private javax.swing.JLabel AddSingleProgressReport;
    private javax.swing.JTable BulkItemTable;
    private javax.swing.JPanel StockPane;
    private javax.swing.JPanel StockSummaryPane;
    private javax.swing.JProgressBar StockSummaryProgress;
    private javax.swing.JLabel StockSummaryProgressReport;
    private javax.swing.JTable StockSummaryTable;
    private javax.swing.JButton addBtnAddBulk;
    private javax.swing.JLabel barcodeAddBulk;
    private javax.swing.JLabel barcodeAddSingle;
    private javax.swing.JTextField designName;
    private javax.swing.JTextField designNameAddBulk;
    private javax.swing.JTextField designNameAddSingle;
    private javax.swing.JTextField designNameSSummary;
    private javax.swing.JButton editUpdateBtn;
    private javax.swing.JButton generateBarcodeAddSingle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JProgressBar mainUiProgress;
    private javax.swing.JLabel mainUiProgressReport;
    private javax.swing.JTextField productID;
    private javax.swing.JTextField productIDAddBulk;
    private javax.swing.JTextField productIDAddSingle;
    private javax.swing.JTextField productIDSSummary;
    private javax.swing.JProgressBar progressBarAddBulk;
    private javax.swing.JLabel progressReportAddBulk;
    private javax.swing.JTextField qty;
    private javax.swing.JTextField qtyAddBulk;
    private javax.swing.JTextField qtyAddSingle;
    private javax.swing.JTextField rackNo;
    private javax.swing.JTextField rackNoAddBulk;
    private javax.swing.JTextField rackNoAddSingle;
    private javax.swing.JButton saveAddSingle;
    private javax.swing.JButton saveAllBtnAddBulk;
    private javax.swing.JButton searchBtn;
    private javax.swing.JButton searchBtnSSummary;
    private javax.swing.JTextField subRackNo;
    private javax.swing.JTextField subRackNoAddBulk;
    private javax.swing.JTextField subRackNoAddSingle;
    private javax.swing.JTextField texture;
    private javax.swing.JTextField textureAddBulk;
    private javax.swing.JTextField textureAddSingle;
    private javax.swing.JButton updateCancleBtn;
    // End of variables declaration//GEN-END:variables

    private void setPanelVisibility(JPanel currentPanel) {
        StockPane.setVisible(false);
        StockSummaryPane.setVisible(false);
        AddSingleItemPane.setVisible(false);
        AddBulkItemPane.setVisible(false);
        currentPanel.setVisible(true);
    }

    private boolean validateNumberInput(String num) {
        boolean isValid = false;
        for(char c : num.toCharArray())
            if(c < '0' || c > '9')
                return isValid;
        isValid = true;
        return isValid;
    }
}
